import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import MovieList from '../components/MovieList'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Micro Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MovieList />
      </main>
    </div>
  )
}

export default Home
