import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useInfiniteQuery } from 'react-query'
import MovieService from '../services/movieService'
import styles from '../styles/Home.module.scss'
import MovieItem from '../components/MovieItem'

const Home: NextPage = () => {
  const { data, isLoading, fetchNextPage, hasNextPage, isFetchingNextPage } = useInfiniteQuery(
    ['movies'],
    MovieService.getAllMovies,
    {
      getNextPageParam: (lastPage, pages) => lastPage.offset <= lastPage.totalItems ? lastPage.offset + 3 : undefined
    }
  )
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Micro Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isLoading ? (
          <p className={styles.center}>Loading...</p>
        ) : (
          data?.pages ? (
            <>
              {data?.pages.map(page => {
                return page.movies.map(movie => (
                  <MovieItem item={movie} key={movie._id} />
                ))
              })}
              {hasNextPage && <div className={styles.center}>
                <button
                  onClick={() => fetchNextPage()}
                  disabled={!hasNextPage || isFetchingNextPage}
                >Load more</button>
              </div>}
            </>
          ) : (
            <p className={styles.center}>No video available</p>
          )
        )}
      </main>
    </div>
  )
}

export default Home
